version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 60
    volumes:
      - postgres:/var/lib/postgresql/data

  mail:
    image: maildev/maildev
    ports:
      - "1080:1080"

  auth:
    image: accent/grpc-service-auth:latest
    environment:
      DB_DNS: postgresql://postgres:password@db:5432/appdb
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/appdb
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/appdb_test
      EMAIL_FROM_ADDRESS: no-reply@example.com
      NOTIFICATIONS_SMTP_HOST: mail
      NOTIFICATIONS_SMTP_PORT: 1025
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app
    command:
      - "/start-reload.sh"
    ports:
      - "80:80"

volumes:
  postgres:
